title: Eric Ko
description: Eric Ko (Eric Long Him Ko) – Product Engineer & Brown University Graduate. Portfolio of AI, systems programming, and software engineering projects.
url: https://ericko.dev
baseurl: ""
author: Eric Ko
image: /images/turtle!.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - wip/
