title: Eric Ko
description: Product Engineer & Brown University Graduate
url: https://ericko.dev
baseurl: ""
author: Eric Ko
image: /images/turtle!.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - wip/
